### ISSUE TITLE
fatal: not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by buhboyvjppro999** [Laupetin/OpenAssetTools#6] opened 2023-09-16 23:55 UTC
Hi, i get an issue. When i click "generate.bat" file, it appears that notification. How can i fix it?

**Comment by Laupetin** [comment] 2023-09-17 08:20
Hi, if you want to build the tools yourself, you will have to clone the git repository with your local git installation:

```shell
git clone https://github.com/Laupetin/OpenAssetTools.git
```

This is due to the dependencies being added via git submodules.
Otherwise follow [the rest of the readme](https://github.com/Laupetin/OpenAssetTools#getting-started) the rest of the Readme.
I will add the cloning part to the README as well.

**Comment by buhboyvjppro999** [comment] 2023-09-22 10:51
ok thanks, but when i use your linker to build fast file i had a problem, it said "Error: code_post_gfx L1234:1 Could not parse expression:". So is it possible to localize .str file? I use it for IW4.

**Comment by JezuzLizard** [comment] 2023-09-23 20:56
> ok thanks, but when i use your linker to build fast file i had a problem, it said "Error: code_post_gfx L1234:1 Could not parse expression:". So is it possible to localize .str file? I use it for IW4.

Its possible the string/ref you are trying to parse is using a currently unsupported character(s) so the parser doesn't handle it.

**Comment by Laupetin** [comment] 2023-09-24 14:03
> ok thanks, but when i use your linker to build fast file i had a problem, it said "Error: code_post_gfx L1234:1 Could not parse expression:". So is it possible to localize .str file? I use it for IW4.

Yes you can use localize files. There was a syntax error in yours apparently. You didn't include the log part where it told you what it was however since that is logged below. It's in Line 1234 in your file though.
If you need help with using the tool feel free to ask me on discord: `@laupetin`.

I'd close this issue for now since this is not a bug or feature request or something.

**Closed by Laupetin** 2023-09-24 14:03 UTC
